services:
  - type: web
    name: django-project
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn blog_project.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.2
      - key: DJANGO_SETTINGS_MODULE
        value: blog_project.settings
      - key: SECRET_KEY
        value: your-secret-key-here